### PR TITLE
Eran/pic 4112 Changed healthcheck interval to 60 seconds

### PR DESCRIPTION
**Pull request by eranco74**
DON'T MERGE!
This is just for review, master branch is way off...

### CODE REVIEW

**Comment by romfreiman** [comment]
The only question is whether we really want to upgrade docker-registry - it will move, and all the images will be deleted during upgrade. Does it worth it? :) Maybe it's better not to touch it for now?
@igal-stratoscale @eran-stratoscale

**Comment by eranco74** [comment]
It will move and the node with updatemangerapi will push all the required images.
I think it's good since it will clean it up.
Currently we don't have a cleanup and the registry holds old images that just take space.

**Comment by romfreiman** [comment]
It will not really clean up because the directory is still there.

**Comment by eranco74** [comment]
I can update the installer/RPM.

**Comment by eranco74** [comment]
Added cleanup to the RPM.

**Pull request merged**
